---
- hosts: app_vm
  become: true
  tasks:
    - name: Deploy 4dvop-nginx
      docker_container:
        name: nginx
        hostname: nginx
        image: 61231/4dvop-nginx
        state: started
        ports:
          - "8080:8080"
    - name: Deploy 4dvop-haproxy
      docker_container:
        name: haproxy
        hostname: haproxy
        image: adriengaultier/4dvop-haproxy
        state: started
        links:
          - nginx:nginx
        ports:
          - "80:80"
